os:
  - linux
  - linux-ppc64le
sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
matrix:
  exclude:
  - os: linux-ppc64le
    node_js: "0.10"
  - os: linux-ppc64le
    node_js: "0.12"
